// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qhnggwscctqpwbdcvgzn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFobmdnd3NjY3RxcHdiZGN2Z3puIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NTU1MzQsImV4cCI6MjA2MDEzMTUzNH0.9NKjeOkMUy67F68ohcptA6CLLWfondT6C4df6W3ssho";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);